# Generated by Django 6.0.3 on 2026-03-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersession_apikey_expires_at_apikey_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apikey',
            name='accounts_ap_key_d955e0_idx',
        ),
        migrations.AddField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['prefix'], name='accounts_ap_prefix_500cff_idx'),
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='key',
        ),
    ]
