# Generated by Django 6.0.3 on 2026-03-18 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('api_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_catalog.apiendpoint')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.apikey')),
            ],
            options={
                'indexes': [models.Index(fields=['api'], name='request_log_api_id_147ea5_idx'), models.Index(fields=['api_key'], name='request_log_api_key_93f0f7_idx'), models.Index(fields=['status_code'], name='request_log_status__e1e460_idx'), models.Index(fields=['created_at'], name='request_log_created_44ff6f_idx'), models.Index(fields=['method'], name='request_log_method_8a6adc_idx'), models.Index(fields=['path'], name='request_log_path_32651e_idx')],
            },
        ),
    ]
