# Generated by Django 4.2.10 on 2026-03-17 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIPlayground',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('method', models.CharField(max_length=10)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_catalog.apiendpoint')),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
